apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-test-binding
  namespace: testify
subjects:
  - kind: ServiceAccount
    name: default
    namespace: testify
roleRef:
  kind: Role
  name: k6-test-role
  apiGroup: rbac.authorization.k8s.io
  