apiVersion: v1
kind: Secret
metadata:
  name: testify-secret
  namespace: testify
type: Opaque
stringData:
  DATABASE_PASSWORD: 'testify'
  DATABASE_URL: 'postgresql://testify:testify@host.docker.internal:5432/testify?schema=public'

  REDIS_PASSWORD: 'testify'
  REDIS_URL: 'rediss://testify:testify@host.docker.internal:6379'

  ACCESS_TOKEN_SECRET: 'testify-access-token-secret'
  REFRESH_TOKEN_SECRET: 'testify-refresh-token-secret'

  GMAIL_APP_PASSWORD: 'qwnf vxxf ppqh akje'

  INFLUXDB_USERNAME: ''
  INFLUXDB_PASSWORD: ''
  INFLUXDB_TOKEN: ''
  INFLUXDB_ADMIN_PASSWORD: 'testify-password'
